// Mock data for the Amazon-inspired marketplace

import { Product, Seller, Review, ShippingOption, PaymentMethod } from './types';

// Mock Sellers
export const mockSellers: Seller[] = [
  {
    id: '1',
    name: 'Tech Solutions LLC',
    rating: 4.8,
    totalSales: 2847,
    joinedDate: '2020-05-15',
    verified: true,
  },
  {
    id: '2',
    name: 'Home Essentials Co',
    rating: 4.6,
    totalSales: 1923,
    joinedDate: '2019-08-22',
    verified: true,
  },
  {
    id: '3',
    name: 'Fashion Forward',
    rating: 4.7,
    totalSales: 3156,
    joinedDate: '2021-01-10',
    verified: true,
  },
  {
    id: '4',
    name: 'Sports Gear Pro',
    rating: 4.9,
    totalSales: 4521,
    joinedDate: '2018-03-05',
    verified: true,
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Headphones Pro',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life, superior sound quality, and comfortable over-ear design.',
    price: 199.99,
    originalPrice: 299.99,
    category: 'Electronics',
    image: '/generated/headphones.png',
    rating: 4.7,
    reviewCount: 2384,
    inStock: true,
    seller: mockSellers[0],
    specifications: {
      'Battery Life': '30 hours',
      'Connectivity': 'Bluetooth 5.0',
      'Noise Cancelling': 'Active',
      'Weight': '250g',
    },
  },
  {
    id: '2',
    name: 'Premium Denim Jacket',
    description: 'Classic blue denim jacket with a modern fit. Perfect for layering, made from high-quality cotton denim.',
    price: 89.99,
    category: 'Fashion',
    image: '/generated/jacket.png',
    rating: 4.5,
    reviewCount: 1456,
    inStock: true,
    seller: mockSellers[2],
    specifications: {
      'Material': '100% Cotton Denim',
      'Fit': 'Regular',
      'Care': 'Machine Washable',
    },
  },
  {
    id: '3',
    name: 'Athletic Running Shoes',
    description: 'Lightweight running shoes with advanced cushioning technology. Breathable mesh upper and durable rubber outsole.',
    price: 79.99,
    originalPrice: 120.00,
    category: 'Sports',
    image: '/generated/sneakers.png',
    rating: 4.8,
    reviewCount: 3127,
    inStock: true,
    seller: mockSellers[3],
    specifications: {
      'Weight': '220g per shoe',
      'Drop': '8mm',
      'Upper': 'Breathable Mesh',
      'Sole': 'Rubber',
    },
  },
  {
    id: '4',
    name: 'Laptop Pro 15 Inch',
    description: 'Powerful laptop with Intel i7 processor, 16GB RAM, 512GB SSD. Perfect for work and entertainment.',
    price: 1299.99,
    category: 'Electronics',
    image: '/generated/laptop.png',
    rating: 4.9,
    reviewCount: 987,
    inStock: true,
    seller: mockSellers[0],
    specifications: {
      'Processor': 'Intel Core i7',
      'RAM': '16GB DDR4',
      'Storage': '512GB SSD',
      'Display': '15.6" Full HD',
    },
  },
  {
    id: '5',
    name: 'Coffee Maker Deluxe',
    description: 'Programmable coffee maker with thermal carafe. Brews up to 12 cups with customizable strength settings.',
    price: 89.99,
    category: 'Home & Garden',
    image: '/generated/coffee-maker.png',
    rating: 4.4,
    reviewCount: 856,
    inStock: true,
    seller: mockSellers[1],
    specifications: {
      'Capacity': '12 cups',
      'Features': 'Programmable, Auto Shutoff',
      'Carafe': 'Thermal Stainless Steel',
    },
  },
  {
    id: '6',
    name: 'Smart Watch Fitness Tracker',
    description: 'Advanced smartwatch with heart rate monitoring, GPS tracking, and 7-day battery life. Water resistant up to 50m.',
    price: 249.99,
    originalPrice: 349.99,
    category: 'Electronics',
    image: '/generated/smartwatch.png',
    rating: 4.6,
    reviewCount: 2145,
    inStock: true,
    seller: mockSellers[0],
    specifications: {
      'Display': '1.4" AMOLED',
      'Battery': '7 days',
      'Water Resistance': '50m',
      'Sensors': 'Heart Rate, GPS, SpO2',
    },
  },
  {
    id: '7',
    name: 'Ergonomic Office Chair',
    description: 'Premium mesh office chair with lumbar support, adjustable armrests, and breathable design for all-day comfort.',
    price: 299.99,
    category: 'Home & Garden',
    image: '/generated/office-chair.png',
    rating: 4.7,
    reviewCount: 1678,
    inStock: true,
    seller: mockSellers[1],
    specifications: {
      'Material': 'Mesh & Metal',
      'Weight Capacity': '300 lbs',
      'Adjustable': 'Height, Armrests, Tilt',
      'Warranty': '5 years',
    },
  },
  {
    id: '8',
    name: 'Bluetooth Speaker Portable',
    description: 'Compact wireless speaker with 360° sound, 20-hour battery, and waterproof design. Perfect for outdoor adventures.',
    price: 59.99,
    originalPrice: 89.99,
    category: 'Electronics',
    image: '/generated/headphones.png',
    rating: 4.5,
    reviewCount: 1234,
    inStock: true,
    seller: mockSellers[0],
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userName: 'Sarah M.',
    rating: 5,
    title: 'Excellent quality, fast shipping!',
    comment: 'These headphones are amazing! The noise cancellation works perfectly and the battery lasts all day. Highly recommend!',
    date: '2024-01-15',
    helpful: 42,
    verified: true,
  },
  {
    id: '2',
    productId: '1',
    userName: 'John D.',
    rating: 4,
    title: 'Great product, minor packaging issue',
    comment: 'Sound quality is excellent, but the packaging was slightly damaged on arrival. Product itself is perfect though.',
    date: '2024-01-10',
    helpful: 23,
    verified: true,
  },
  {
    id: '3',
    productId: '2',
    userName: 'Emily R.',
    rating: 5,
    title: 'Perfect fit and style',
    comment: 'This jacket fits perfectly and looks great with everything. The quality is outstanding for the price.',
    date: '2024-01-12',
    helpful: 18,
    verified: true,
  },
  {
    id: '4',
    productId: '3',
    userName: 'Mike T.',
    rating: 5,
    title: 'Best running shoes I\'ve owned',
    comment: 'Super comfortable and lightweight. Great for long-distance running. My feet don\'t hurt anymore!',
    date: '2024-01-08',
    helpful: 67,
    verified: true,
  },
];

// Shipping Options
export const shippingOptions: ShippingOption[] = [
  {
    id: 'standard',
    name: 'Standard Delivery',
    price: 0,
    estimatedDays: '3-5 business days',
  },
  {
    id: 'express',
    name: 'Express Delivery',
    price: 9.99,
    estimatedDays: '1-2 business days',
  },
  {
    id: 'overnight',
    name: 'Overnight Delivery',
    price: 19.99,
    estimatedDays: 'Next business day',
  },
];

// Payment Methods
export const paymentMethods: PaymentMethod[] = [
  {
    id: 'credit-card',
    name: 'Credit Card',
    icon: '💳',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    icon: '🅿️',
  },
  {
    id: 'apple-pay',
    name: 'Apple Pay',
    icon: '🍎',
  },
  {
    id: 'google-pay',
    name: 'Google Pay',
    icon: '🔷',
  },
];
